IF DB_ID('BattleShipDb') IS NULL CREATE DATABASE BattleShipDb;
GO
USE BattleShipDb;
GO
IF OBJECT_ID('dbo.Users') IS NULL CREATE TABLE dbo.Users (Id INT IDENTITY PRIMARY KEY, Username NVARCHAR(50) NOT NULL UNIQUE, PasswordHash NVARCHAR(255) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Games') IS NULL CREATE TABLE dbo.Games (Id BIGINT IDENTITY PRIMARY KEY, UserId INT NOT NULL, Difficulty NVARCHAR(20) NOT NULL, Result NVARCHAR(20) NOT NULL, StartedAt DATETIME2 NOT NULL, FinishedAt DATETIME2 NULL, Shots INT NOT NULL DEFAULT 0, CONSTRAINT FK_Games_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id));
IF OBJECT_ID('dbo.Shots') IS NULL CREATE TABLE dbo.Shots (Id BIGINT IDENTITY PRIMARY KEY, GameId BIGINT NOT NULL, Actor NVARCHAR(10) NOT NULL, RowIndex INT NOT NULL, ColumnIndex INT NOT NULL, Result NVARCHAR(20) NOT NULL, FiredAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_Shots_Games FOREIGN KEY (GameId) REFERENCES dbo.Games(Id));
GO
