<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="..\BattleShip.Domain\BattleShip.Domain.csproj" /><PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" /></ItemGroup></Project>
